on:
  pull_request:
    types: [opened, reopened]

jobs:
  pr_preview_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Example of message !'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
